name: Update GeoIP2-CN

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 */3 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Update GeoIP2 database
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: openssl

      # Runs a single command using the runners shell
      - name: Update GeoIP2 database
        run: php ./main.php

      - name: Push artifacts to release branch
        run: |
          git config --local user.email "49953737+v03413@users.noreply.github.com"
          git config --local user.name "github-action[bot]"
          git fetch
          git checkout release
          git checkout --orphan release-orphan
          git rm -rf .
          git add ./dst/China_IP_list.txt
          git commit -am "Updated at $(date)"
          git branch -D release
          git branch -m release

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          force: true

      - name: Purge CDN Cache
        run: curl ${{ secrets.CDN_URL }}